--- #YAML:1.0
name:               DateTime-Set
version:            0.3400
abstract:           DateTime set objects
author:
    - Flavio S. Glock <fglock@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:       0.12
    Set::Infinite:  0.59
    Test::More:     0
resources:
    repository:
        type:  git
        url:   https://github.com/fglock/DateTime-Set.git
        web:   https://github.com/fglock/DateTime-Set
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  2
