--- #YAML:1.0
name: DateTime-Set
version: 0.1410
author:
  - Flavio S. Glock <fglock@pucrs.br>
abstract: DateTime set objects
license: perl
requires:
  DateTime: 0.12
  Params::Validate: 0
  Set::Infinite: 0.5503
  Test::More: 0
conflicts:
  DateTime::Event::Cron: '<= 0.06'
  DateTime::Event::ICal: '< 0.07'
  DateTime::Event::Random: '< 0.03'
  DateTime::Event::Recurrence: '< 0.10'
  DateTime::Event::Sunrise: '< 0.05'
provides:
  DateTime::Set:
    file: lib/DateTime/Set.pm
    version: 0.1410
  DateTime::Span:
    file: lib/DateTime/Span.pm
  DateTime::SpanSet:
    file: lib/DateTime/SpanSet.pm
  Set::Infinite::_recurrence:
    file: lib/Set/Infinite/_recurrence.pm
generated_by: Module::Build version 0.23
